### ISSUE TITLE
rh-cloud-base.repo with wrong entries or empty

### ISSUE THREAD

**Issue by divargas-msft** [adelgadohell/rhui_test#1]
Wwhen /etc/yum.repos.d/rh-cloud-base.repo file is empty or incorrect entries, need to add a test case or message for it. As the displayed message is incorrect or doesn't help customer.

```
Traceback (most recent call last):

 File "rhui_test.py", line 382, in <module>

   eus = check_microsoft_repo(reposconfig)

 File "rhui_test.py", line 161, in check_microsoft_repo

   if myreponame:

UnboundLocalError: local variable 'myreponame' referenced before assignment
```

**Comment by esvmicrosoft** [comment]
this version already addresses the issue with an empty file or invalid entries.

**Comment by divargas-msft** [comment]
This was already tested by Arun, closing this issue
