### ISSUE TITLE
Invalid destination for RHUI servers - Improve the root cause identification and message

### ISSUE THREAD

**Issue by divargas-msft** [adelgadohell/rhui_test#2]
Test case to validate if /etc/hosts has any references to rhui4-1.microsoft.com. As having some static entries in /etc/hosts file is not producing meaningful messages with the script execution.
 

Example: Added "8.8.8.8 rhui4-1.microsoft.com" line in /etc/hosts and the script produced below message.

 

```
CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, reinstall the RHUI package

CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers
```

**Comment by divargas-msft** [comment]
Test:  10 Hardcoded wrong IP for RHUI-4 on /etc/hosts

https://dev.azure.com/LinuxNinjas/15c84587-281d-4d8d-ad04-bb7e3dbdcd73/_apis/wit/attachments/310a7f42-1f7c-4748-91eb-5490c9dc0eef?fileName=image.png

https://dev.azure.com/LinuxNinjas/15c84587-281d-4d8d-ad04-bb7e3dbdcd73/_apis/wit/attachments/f288542f-25d5-42f9-a7ff-4a3ac3536ad4?fileName=image.png

**Comment by divargas-msft** [comment]
@arunkp89  will be working on this one

**Comment by arunkp89** [comment]
When having a static "8.8.8.8 rhui4-1.microsoft.com" entry for rhui in /etc/hosts, we are getting below error. Although the error says rhui is pointing to invalid destination, maybe we should also add something about the /etc/hosts contents??

CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, reinstall the RHUI package
CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

**Comment by arunkp89** [comment]
Modified the code to include change the message being displayed if there is a static entry in /etc/hosts file.
Need someone to validate this again.

CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, validate /etc/hosts file for any static RHUI IPs, reinstall the RHUI package

**Comment by msaenzbosupport** [comment]
@msaenzbosupport  Will test it.

**Comment by msaenzbosupport** [comment]
@arunkp89 @esvmicrosoft 

Still seeing 2 messages for this issue:

https://dev.azure.com/LinuxNinjas/SelfHelp/_workitems/edit/2916/

CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, validate /etc/hosts file for any static RHUI IPs, reinstall the RHUI package
CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

**Comment by arunkp89** [comment]
@msaenzbosupport  after Enrique fixed the issue with empty /etc/hosts, **_below_** is the only change I made. So we were expecting 2 messages for this failure.

**BEFORE**
CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, reinstall the RHUI package
CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

**CURRENT**

CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, _**validate /etc/hosts file for any static RHUI IPs**_, reinstall the RHUI package
CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

**Comment by msaenzbosupport** [comment]
@arunkp89 Can we remove this, false positive? 

CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

**Comment by arunkp89** [comment]
I think the second criteria is coming from a different condition of unable to connect to RHUI ? will need to check the code again. @esvmicrosoft might have a better way to make this change/comment.

**Comment by arunkp89** [comment]
I think the second criteria is coming from a different condition of unable to connect to RHUI, will need to check the code again. @esvmicrosoft might have a better way to implement this.

**Comment by msaenzbosupport** [comment]
@esvmicrosoft 

During the call we have the following discussion.

After the script check the /etc/host file is keeping the bad rhui address rhui_ip_address = socket.gethostbyname(url_host) 
and use it to test other things that are causing a false positive as below

CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers

Can we change the way we are doing it? After the script found that issue, can the script continue doing other validations using the correct RHUI IP?

**Comment by divargas-msft** [comment]
This one is still pending. The ask is to stop doing other validations if it has been determined there's an error with the IP being used in /etc/hosts. The first msg is correct, the second one is misleading/incorrect:

CRITICAL:root:RHUI server rhui4-1.microsoft.com points to an invalid destination, validate /etc/hosts file for any static RHUI IPs, reinstall the RHUI package


**CRITICAL:root:PROBLEM: Cannot communicate with any RHUI server, you must allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers**

**Comment by divargas-msft** [comment]
The message could be switched to "CRITICAL:root:PROBLEM: Make sure you allow at least one of the IP addresses listed here https://learn.microsoft.com/azure/virtual-machines/workloads/redhat/redhat-rhui?tabs=rhel9#the-ips-for-the-rhui-content-delivery-servers"

**Comment by divargas-msft** [comment]
@esvmicrosoft  to double if this one was modified and let us know, so @msaenzbosupport  can retest

**Comment by divargas-msft** [comment]
Still pending @esvmicrosoft

**Comment by divargas-msft** [comment]
This has been resolved by @esvmicrosoft
