### ISSUE TITLE
Add script logging 

### ISSUE THREAD

**Issue by divargas-msft** [adelgadohell/rhui_test#3]
When the script fails, it gives the public URL of what has failed and the actions customer need to take to fix the issue. It would be helpful if we can also put that message into a file for support reference, so that our frontline support can see if the customer has really gone through the steps provided by the script (inside /var/log).

**Comment by arunkp89** [comment]
Added a start_logging() function to capture the script output to /var/log/rhuiscript.log file.

**Comment by arunkp89** [comment]
Modified the logging file name to /var/log/rhuicheck.log

**Comment by divargas-msft** [comment]
@msaenzbosupport to test this one.

**Comment by divargas-msft** [comment]
This has been fixed
