### ISSUE TITLE
Bug - Currently not validating e4s repos 

### ISSUE THREAD

**Issue by divargas-msft** [adelgadohell/rhui_test#4]
I notice is that is not validating e4s repos... also we are getting output that /etc/yum/vars/releasever does not exit but it exists...

https://dev.azure.com/LinuxNinjas/15c84587-281d-4d8d-ad04-bb7e3dbdcd73/_apis/wit/attachments/fa4b8a50-0e51-42a0-839b-d3a1f4184b6e?fileName=image.png

**Comment by esvmicrosoft** [comment]
just realized machines with e4s repos have 2 rhui rpms

**Comment by divargas-msft** [comment]
This one has been retested and it's still failing: https://dev.azure.com/LinuxNinjas/SelfHelp/_workitems/edit/2828

**Comment by divargas-msft** [comment]
Enrique pushed a code change, Mau will be retesting this one

**Comment by msaenzbosupport** [comment]
https://dev.azure.com/LinuxNinjas/SelfHelp/_workitems/edit/2828/

Looks the
leapp-rhui-azure-sap-1.0.0-10.el8.noarch  
the leapp rhui azure sap rpm is causing the issue...  this is for a test that I did for a VM that was migrated from RHEL 8.8 to 9.2 SAP HA.

Enrique is taking a look.

**Comment by divargas-msft** [comment]
This one is still pending, Enrique will take a look after the EUS bug is fixed

**Comment by divargas-msft** [comment]
@msaenzbosupport will be testing this one

**Comment by divargas-msft** [comment]
This test has been passed, closing this issue
