### ISSUE TITLE
Bug - SSL validation stops working if crypto policy is changed

### ISSUE THREAD

**Issue by divargas-msft** [adelgadohell/rhui_test#5]
crypto-policies changed to Future, this will prevent ssl connection.   :  https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux/troubleshoot-linux-rhui-certificate-issues?tabs=rhel9-eus%2crhel9-noneus%2crhe79-rhel-sap-ha%2crhel8-rhel-sap-apps%2crhel9-rhel-sap-apps#cause-5-verification-error-in-rhel-version-8-or-9-ca-certificate-key-too-weak

https://dev.azure.com/LinuxNinjas/15c84587-281d-4d8d-ad04-bb7e3dbdcd73/_apis/wit/attachments/77fdaf96-8523-48de-a4b4-625016e2a27e?fileName=image.png

**Comment by divargas-msft** [comment]
This one is ready to test @arunkp89 will help to test it, @msaenzbosupport also help to test this one.

**Comment by divargas-msft** [comment]
Enrique pending to push the changes to this version of the repo, let us know once in sync so Arun can test it

**Comment by divargas-msft** [comment]
Code changes were already pushed, this is pending to be tested by @arunkp89

**Comment by arunkp89** [comment]
Setting Crypto policy to other than DEFAULT is returning the proper message. Below is what I got when setting crypto policy to FUTURE.

CRITICAL:root:Client crypto policies not set to DEFAULT
CRITICAL:root:Refer to: https://learn.microsoft.com/troubleshoot/azure/virtual-machines/linux/troubleshoot-linux-rhui-certificate-issues?tabs=rhel7-eus%2Crhel7-noneus%2Crhel7-rhel-sap-apps%2Crhel8-rhel-sap-apps%2Crhel9-rhel-sap-apps#cause-5-verification-error-in-rhel-version-8-or-9-ca-certificate-key-too-weak

**Comment by msaenzbosupport** [comment]
@arunkp89  Tested.  Working as expected.
