### ISSUE TITLE
Remove RHUI [1-3] IP's - Confirmation from PG that are retired.

### ISSUE THREAD

**Issue by msaenzbosupport** [adelgadohell/rhui_test#8]
RHUI 1 2 3 IPs are retired.
RHUI 1 2 3 FQDN still pointing RHUI 4 IPS.

We need to update the script.

**Comment by esvmicrosoft** [comment]
code updated, pls test

**Comment by divargas-msft** [comment]
task assigned to Mauricio to test this, then this one will be ready to close

**Comment by divargas-msft** [comment]
testing passed, closing this one
